language: php
php:
  - '7.0'
  - nightly
before_script: composer install --dev && composer update
script:
  - mkdir -p build/logs  
  - ./vendor/bin/phpunit -c phpunit.xml
after_script:
  - php vendor/bin/php-coveralls -v
